# Generated by Django 4.1 on 2022-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('House', 'House'), ('Job', 'Job'), ('Food', 'Food'), ('Phone', 'Phone'), ('School', 'School'), ('Computer', 'Computer'), ('Garden', 'Garden')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='message',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
