# Generated by Django 4.1 on 2022-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_category_posts_date_posts_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagelink',
            field=models.URLField(max_length=250),
        ),
    ]
