# Generated by Django 4.1 on 2022-08-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_publishedposts_publishedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule',
            field=models.BooleanField(default='False'),
        ),
    ]
