# Generated by Django 4.1 on 2022-08-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='design_link',
            field=models.ImageField(blank=True, null=True, upload_to='images/designs/'),
        ),
    ]
