# Generated by Django 4.1 on 2022-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_design_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
