# Generated by Django 4.1 on 2022-08-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_profile_timezone'),
        ('posts', '0015_schedule_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedpost',
            name='date_to_publish',
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='publisded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
            preserve_default=False,
        ),
    ]
