# Generated by Django 4.1 on 2022-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_publishedpost_date_to_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
