# Generated by Django 4.1 on 2022-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_schedule_scheduled_by_alter_schedule_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedpost',
            name='publisded_by',
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='scheduled_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
