# Generated by Django 4.1 on 2022-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_publishedpost_scheduled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='design_link',
            field=models.ImageField(blank=True, null=True, upload_to='images/designs/'),
        ),
    ]
