# Generated by Django 4.1 on 2022-08-21 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('Algeria', 'Algeria'), ('Bahrain', 'Bahrain'), ('Comoros', 'Comoros'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Iraq', 'Iraq'), ('Jordan', 'Jordan'), ('Kuwait', 'Kuwait'), ('Lebanon', 'Lebanon'), ('Libya', 'Libya'), ('Mauritania', 'Mauritania'), ('Morocco', 'Morocco'), ('Oman', 'Oman'), ('Saudi Arabia', 'Saudi Arabia'), ('Sudan', 'Sudan'), ('Syria', 'Syria'), ('Tunisia', 'Tunisia'), ('United Arab Emirates', 'United Arab Emirates'), ('Yemen', 'Yemen')], max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_ur', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True)),
                ('skype_url', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
