# Generated by Django 4.1 on 2022-08-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_ur',
            new_name='facebook_url',
        ),
    ]
