# Generated by Django 4.1 on 2022-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_facebook_ur_profile_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_link',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
