# Generated by Django 4.1 on 2022-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_link',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
