# Generated by Django 4.1 on 2022-08-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_link',
        ),
    ]
